name: CI

on:
  push:
    branches: "master"
    tags: ["*"]
  pull_request:
  release:

env:
  # `reproject=0.5` is not compatible with Python >= 3.8
  PYTHON: "python3.7"

jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }} - ${{ matrix.julia-arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version:
          - "1.0"
          - "1"
          - "nightly"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        julia-arch:
          - x64
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-uploadcodecov@v0.1
        continue-on-error: true
      - uses: julia-actions/julia-uploadcoveralls@v0.1
        continue-on-error: true
