name: CompatHelper
on:
  schedule:
    - cron: 59 14 * * *
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Add the General registry via Git"
        shell: julia --color=yes {0}
        run: |
          import Pkg
          ENV["JULIA_PKG_SERVER"] = ""
          Pkg.Registry.add("General")
      - name: "Install CompatHelper"
        shell: julia --color=yes {0}
        run: |
          import Pkg
          name = "CompatHelper"
          uuid = "aa819f21-2bde-4658-8897-bab36330d9b7"
          version = "3"
          Pkg.add(; name, uuid, version)
      - name: "Run CompatHelper"
        shell: julia --color=yes {0}
        run: |
          import CompatHelper
          CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
